version: '3'


services: 
    app:
        container_name: iroha_app
        build: ./app
        tty: true
        restart: always
        # ports: 
            # - 80:80
            # Please use if you need ssl.
            # - 443:443
        environment:
            VIRTUAL_HOST: #change to your server address.
            LETSENCRYPT_HOST: #change to your servier address.
            LETSENCRYPT_EMAIL: #change to your mail address.
        depends_on: 
            - db
        volumes:
            - ./uploads:/var/www/html/app/webroot/uploads

    db:
        container_name: iroha_db
        build: ./db
        environment:
            MYSQL_ROOT_PASSWORD: rootp@ss
            MYSQL_DATABASE: irohaboard
            MYSQL_USER: iroha
            MYSQL_PASSWORD: iroha
        # ports:
        #     - 3306:3306
        volumes:
          - ./db/data:/var/lib/mysql
    nginx-proxy:
        image: jwilder/nginx-proxy # 独自 Docker ファイルをやめる
        restart: on-failure
        # ラベルを追加
        labels:
          - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=jwilder/nginx-proxy
        container_name: nginx-proxy
        privileged: true
        ports:
          - "80:80"
          - "443:443" # ポート追加
        # ボリュームを追加
        volumes:
          - proxy:/etc/nginx/vhost.d
          - proxy:/usr/share/nginx/html
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./certs:/etc/nginx/certs:ro
          - ./server.conf:/etc/nginx/conf.d/server.conf

    letsencrypt: 
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: on-failure
        container_name: letsencrypt-nginx
        depends_on:
          - nginx-proxy
        volumes:
          - proxy:/etc/nginx/vhost.d
          - proxy:/usr/share/nginx/html
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ./certs:/etc/nginx/certs:rw

volumes:
    proxy:
